### ISSUE TITLE
[Request] Neochat

### ISSUE THREAD

**Issue by SViN24** [ScoopInstaller/Nightlies#6]
Based on https://github.com/ScoopInstaller/Extras/issues/7283
application is currently in development on windows and not stable, thus it should go to nightlies.

---

### Information

**Name:** neochat

**Description:** neochat is a matrix client by KDE, it also has an active windows port since it is multiplatform.

**Homepage:** main git repo: https://invent.kde.org/network/neochat

**Download link(s):** build repo https://binary-factory.kde.org/job/NeoChat_Nightly_win64/

**Some indication of popularity/repute:** in the github mirror repo there are 72 stars, in the private repo there is a healthy amount of issues(157 active,314 closed) and activity.

**Comment by tech189** [comment]
> Nightlies bucket is no longer recommended/used. All nightly apps should be submitted to Versions.

Submitted a PR in Versions: https://github.com/ScoopInstaller/Versions/pull/339

**Comment by tech189** [comment]
@SViN24 you can now install with `scoop update && scoop install neochat-nightly`!
