### ISSUE TITLE
Move dotnet-nightly to Versions

### ISSUE THREAD

**Issue by tech189** [ScoopInstaller/Nightlies#7]
Since this bucket is no longer recommended for nightlies (see [here](https://github.com/ScoopInstaller/Extras/issues/7283#issuecomment-987875375)) and since Versions is preferred, we should move the dotnet-nightly manifest to the Versions bucket. And maybe we should leave a note in the Readme for anyone still using Nightlies to move to Versions?

BTW just tested, the dotnet-nightly manifest works fine for me even though it hasn't been updated in 13 months.

**Comment by rashil2000** [comment]
Sure, we can add a note in manifests here
